# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1162, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.UniverseSelect = QtWidgets.QComboBox(self.centralwidget)
        self.UniverseSelect.setGeometry(QtCore.QRect(40, 40, 121, 31))
        self.UniverseSelect.setObjectName("UniverseSelect")
        self.UniverseSelect.addItem("")
        self.UniverseSelect.addItem("")
        self.UniverseSelect.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.startDate = QtWidgets.QDateEdit(self.centralwidget)
        self.startDate.setGeometry(QtCore.QRect(240, 40, 110, 32))
        self.startDate.setDate(QtCore.QDate(2010, 1, 1))
        self.startDate.setCalendarPopup(True)
        self.startDate.setObjectName("startDate")
        self.endDate = QtWidgets.QDateEdit(self.centralwidget)
        self.endDate.setGeometry(QtCore.QRect(410, 40, 110, 32))
        self.endDate.setDate(QtCore.QDate(2015, 1, 1))
        self.endDate.setCalendarPopup(True)
        self.endDate.setObjectName("endDate")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(410, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 530, 231, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 180, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.minW = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.minW.setGeometry(QtCore.QRect(30, 220, 71, 32))
        self.minW.setDecimals(4)
        self.minW.setSingleStep(0.0001)
        self.minW.setObjectName("minW")
        self.maxW = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.maxW.setGeometry(QtCore.QRect(120, 220, 71, 32))
        self.maxW.setDecimals(4)
        self.maxW.setMaximum(1.0)
        self.maxW.setSingleStep(0.0001)
        self.maxW.setProperty("value", 0.1)
        self.maxW.setObjectName("maxW")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 260, 52, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(130, 260, 52, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 470, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(220, 180, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 120, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 160, 521, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(290, 220, 62, 32))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(6)
        self.spinBox.setObjectName("spinBox")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(300, 260, 52, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setItalic(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(190, 10, 20, 91))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(430, 180, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setGeometry(QtCore.QRect(450, 220, 62, 32))
        self.spinBox_2.setMinimum(3)
        self.spinBox_2.setMaximum(48)
        self.spinBox_2.setProperty("value", 12)
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(460, 260, 52, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setItalic(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, 390, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(20, 430, 521, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.Button_Import_Data = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Import_Data.setGeometry(QtCore.QRect(10, 80, 51, 41))
        self.Button_Import_Data.setObjectName("Button_Import_Data")
        self.Button_Import_Compo = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Import_Compo.setGeometry(QtCore.QRect(70, 80, 51, 41))
        self.Button_Import_Compo.setObjectName("Button_Import_Compo")
        self.Button_Import_Index = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Import_Index.setGeometry(QtCore.QRect(130, 80, 51, 41))
        self.Button_Import_Index.setObjectName("Button_Import_Index")
        self.mpl = MplWidget(self.centralwidget)
        self.mpl.setGeometry(QtCore.QRect(560, 10, 601, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        self.mpl.setObjectName("mpl")
        self.Graph_startDate = QtWidgets.QDateEdit(self.centralwidget)
        self.Graph_startDate.setGeometry(QtCore.QRect(580, 510, 110, 32))
        self.Graph_startDate.setDate(QtCore.QDate(2010, 1, 1))
        self.Graph_startDate.setCalendarPopup(True)
        self.Graph_startDate.setObjectName("Graph_startDate")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(750, 480, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.Graph_endDate = QtWidgets.QDateEdit(self.centralwidget)
        self.Graph_endDate.setGeometry(QtCore.QRect(750, 510, 110, 32))
        self.Graph_endDate.setDate(QtCore.QDate(2015, 1, 1))
        self.Graph_endDate.setCalendarPopup(True)
        self.Graph_endDate.setObjectName("Graph_endDate")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(580, 480, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.Graph_Update = QtWidgets.QPushButton(self.centralwidget)
        self.Graph_Update.setGeometry(QtCore.QRect(960, 490, 131, 51))
        self.Graph_Update.setObjectName("Graph_Update")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(540, 10, 20, 541))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(620, 460, 451, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.Button_Add_Port = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Add_Port.setGeometry(QtCore.QRect(440, 320, 81, 51))
        self.Button_Add_Port.setObjectName("Button_Add_Port")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(300, 330, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.Button_Reset = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Reset.setGeometry(QtCore.QRect(440, 470, 81, 31))
        self.Button_Reset.setObjectName("Button_Reset")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(290, 470, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(10, 310, 111, 29))
        self.radioButton.setIconSize(QtCore.QSize(24, 24))
        self.radioButton.setObjectName("radioButton")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(30, 280, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 340, 121, 29))
        self.radioButton_2.setIconSize(QtCore.QSize(24, 24))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(150, 310, 111, 29))
        self.radioButton_3.setIconSize(QtCore.QSize(24, 24))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(150, 340, 111, 29))
        self.radioButton_4.setIconSize(QtCore.QSize(24, 24))
        self.radioButton_4.setObjectName("radioButton_4")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(130, 310, 21, 51))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1162, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.UniverseSelect.setItemText(0, _translate("MainWindow", "MSCI EU"))
        self.UniverseSelect.setItemText(1, _translate("MainWindow", "MSCI Europe"))
        self.UniverseSelect.setItemText(2, _translate("MainWindow", "STOXX 50"))
        self.label.setText(_translate("MainWindow", "Universe"))
        self.startDate.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.endDate.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.label_2.setText(_translate("MainWindow", "Start Date"))
        self.label_3.setText(_translate("MainWindow", "End Date"))
        self.label_4.setText(_translate("MainWindow", "Weight Constraints"))
        self.label_5.setText(_translate("MainWindow", "Minimum"))
        self.label_6.setText(_translate("MainWindow", "Maximum"))
        self.pushButton.setText(_translate("MainWindow", "Launch"))
        self.label_7.setText(_translate("MainWindow", "Rebalancing Frequency"))
        self.label_8.setText(_translate("MainWindow", "Portfolio Parameters"))
        self.label_9.setText(_translate("MainWindow", "Months"))
        self.label_10.setText(_translate("MainWindow", "Historic Length"))
        self.label_11.setText(_translate("MainWindow", "Months"))
        self.label_12.setText(_translate("MainWindow", "Backtest Parameters"))
        self.Button_Import_Data.setText(_translate("MainWindow", "Data"))
        self.Button_Import_Compo.setText(_translate("MainWindow", "Compo"))
        self.Button_Import_Index.setText(_translate("MainWindow", "Index"))
        self.Graph_startDate.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.label_13.setText(_translate("MainWindow", "End Date"))
        self.Graph_endDate.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.label_14.setText(_translate("MainWindow", "Start Date"))
        self.Graph_Update.setText(_translate("MainWindow", "Refresh"))
        self.Button_Add_Port.setText(_translate("MainWindow", "OK"))
        self.label_15.setText(_translate("MainWindow", "Add to Backtest List"))
        self.Button_Reset.setText(_translate("MainWindow", "Reset"))
        self.label_16.setText(_translate("MainWindow", "Reset the Backtest List"))
        self.radioButton.setText(_translate("MainWindow", "Min Variance"))
        self.label_17.setText(_translate("MainWindow", "Strategy "))
        self.radioButton_2.setText(_translate("MainWindow", "Equal Weighted"))
        self.radioButton_3.setText(_translate("MainWindow", "1 / Beta"))
        self.radioButton_4.setText(_translate("MainWindow", "1 / Sigma"))

from mplwidget import MplWidget
