# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project_Design_v3.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1137, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_3.sizePolicy().hasHeightForWidth())
        self.tab_3.setSizePolicy(sizePolicy)
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.mpl = MplWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        self.mpl.setMinimumSize(QtCore.QSize(500, 350))
        self.mpl.setObjectName("mpl")
        self.gridLayout_13.addWidget(self.mpl, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_13, 0, 13, 13, 3)
        self.line_9 = QtWidgets.QFrame(self.tab_3)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_7.addWidget(self.line_9, 0, 6, 3, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 0, 8, 1, 2)
        self.UniverseSelect = QtWidgets.QComboBox(self.tab_3)
        self.UniverseSelect.setObjectName("UniverseSelect")
        self.UniverseSelect.addItem("")
        self.UniverseSelect.addItem("")
        self.UniverseSelect.addItem("")
        self.gridLayout_7.addWidget(self.UniverseSelect, 1, 0, 1, 5)
        self.endDate = QtWidgets.QDateEdit(self.tab_3)
        self.endDate.setCalendarPopup(True)
        self.endDate.setDate(QtCore.QDate(2015, 1, 1))
        self.endDate.setObjectName("endDate")
        self.gridLayout_7.addWidget(self.endDate, 1, 10, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 0, 10, 1, 2)
        self.Button_Import_Data = QtWidgets.QPushButton(self.tab_3)
        self.Button_Import_Data.setObjectName("Button_Import_Data")
        self.gridLayout_7.addWidget(self.Button_Import_Data, 2, 0, 1, 1)
        self.startDate = QtWidgets.QDateEdit(self.tab_3)
        self.startDate.setCalendarPopup(True)
        self.startDate.setDate(QtCore.QDate(2010, 1, 1))
        self.startDate.setObjectName("startDate")
        self.gridLayout_7.addWidget(self.startDate, 1, 8, 1, 2)
        self.label = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 4)
        self.pushButton = QtWidgets.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_7.addWidget(self.pushButton, 14, 0, 2, 7)
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 5, 11, 1, 2)
        self.radioButton_4 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_4.setIconSize(QtCore.QSize(24, 24))
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_7.addWidget(self.radioButton_4, 10, 5, 1, 4)
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 5, 7, 1, 3)
        self.line_7 = QtWidgets.QFrame(self.tab_3)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_7.addWidget(self.line_7, 13, 13, 1, 3)
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 9, 9, 2, 2)
        self.maxW = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.maxW.setDecimals(4)
        self.maxW.setMaximum(1.0)
        self.maxW.setSingleStep(0.0001)
        self.maxW.setProperty("value", 0.1)
        self.maxW.setObjectName("maxW")
        self.gridLayout_7.addWidget(self.maxW, 6, 2, 1, 4)
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 5, 0, 1, 7)
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 3, 0, 1, 8)
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 7, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setItalic(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 7, 9, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.tab_3)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_7.addWidget(self.line_13, 9, 3, 1, 2)
        self.line_11 = QtWidgets.QFrame(self.tab_3)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_7.addWidget(self.line_11, 4, 0, 1, 12)
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_3.setIconSize(QtCore.QSize(24, 24))
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_7.addWidget(self.radioButton_3, 9, 5, 1, 4)
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setItalic(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 7, 11, 1, 1)
        self.Button_Import_Compo = QtWidgets.QPushButton(self.tab_3)
        self.Button_Import_Compo.setObjectName("Button_Import_Compo")
        self.gridLayout_7.addWidget(self.Button_Import_Compo, 2, 1, 1, 2)
        self.label_56 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setItalic(True)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.gridLayout_7.addWidget(self.label_56, 11, 1, 1, 5)
        self.minW = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.minW.setDecimals(4)
        self.minW.setSingleStep(0.0001)
        self.minW.setObjectName("minW")
        self.gridLayout_7.addWidget(self.minW, 6, 0, 1, 2)
        self.spinBox = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(6)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_7.addWidget(self.spinBox, 6, 9, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 7, 3, 1, 3)
        self.label_43 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.gridLayout_7.addWidget(self.label_43, 12, 0, 1, 8)
        self.Button_Import_Index = QtWidgets.QPushButton(self.tab_3)
        self.Button_Import_Index.setObjectName("Button_Import_Index")
        self.gridLayout_7.addWidget(self.Button_Import_Index, 2, 4, 1, 2)
        self.radioButton = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton.setIconSize(QtCore.QSize(24, 24))
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_7.addWidget(self.radioButton, 9, 0, 1, 3)
        self.spinBox_2 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_2.setMinimum(3)
        self.spinBox_2.setMaximum(48)
        self.spinBox_2.setProperty("value", 12)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_7.addWidget(self.spinBox_2, 6, 11, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 14, 9, 1, 2)
        self.Button_Reset = QtWidgets.QPushButton(self.tab_3)
        self.Button_Reset.setObjectName("Button_Reset")
        self.gridLayout_7.addWidget(self.Button_Reset, 14, 11, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 14, 13, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 8, 0, 1, 3)
        self.Button_Add_Port = QtWidgets.QPushButton(self.tab_3)
        self.Button_Add_Port.setObjectName("Button_Add_Port")
        self.gridLayout_7.addWidget(self.Button_Add_Port, 9, 11, 2, 1)
        self.line_12 = QtWidgets.QFrame(self.tab_3)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_7.addWidget(self.line_12, 13, 0, 1, 12)
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_2.setIconSize(QtCore.QSize(24, 24))
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_7.addWidget(self.radioButton_2, 10, 0, 1, 4)
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 14, 14, 1, 1)
        self.Graph_startDate = QtWidgets.QDateEdit(self.tab_3)
        self.Graph_startDate.setCalendarPopup(True)
        self.Graph_startDate.setDate(QtCore.QDate(2010, 1, 1))
        self.Graph_startDate.setObjectName("Graph_startDate")
        self.gridLayout_7.addWidget(self.Graph_startDate, 15, 13, 3, 1)
        self.label_38 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_38.setFont(font)
        self.label_38.setScaledContents(False)
        self.label_38.setObjectName("label_38")
        self.gridLayout_7.addWidget(self.label_38, 15, 9, 3, 1)
        self.Graph_Update = QtWidgets.QPushButton(self.tab_3)
        self.Graph_Update.setObjectName("Graph_Update")
        self.gridLayout_7.addWidget(self.Graph_Update, 14, 15, 3, 1)
        self.Graph_endDate = QtWidgets.QDateEdit(self.tab_3)
        self.Graph_endDate.setCalendarPopup(True)
        self.Graph_endDate.setDate(QtCore.QDate(2015, 1, 1))
        self.Graph_endDate.setObjectName("Graph_endDate")
        self.gridLayout_7.addWidget(self.Graph_endDate, 15, 14, 3, 1)
        self.Button_Save = QtWidgets.QPushButton(self.tab_3)
        self.Button_Save.setObjectName("Button_Save")
        self.gridLayout_7.addWidget(self.Button_Save, 16, 11, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.tab_3)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_7.addWidget(self.progressBar, 16, 0, 1, 7)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_30 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 2, 4, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 2, 5, 1, 1)
        self.mpl_distrib = MplWidget(self.tab_4)
        self.mpl_distrib.setObjectName("mpl_distrib")
        self.gridLayout_4.addWidget(self.mpl_distrib, 9, 5, 2, 1)
        self.label_32 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 8, 5, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_34 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.gridLayout_5.addWidget(self.label_34, 0, 0, 1, 1)
        self.spinBox_drawdown = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_drawdown.setMinimum(30)
        self.spinBox_drawdown.setMaximum(500)
        self.spinBox_drawdown.setSingleStep(10)
        self.spinBox_drawdown.setProperty("value", 90)
        self.spinBox_drawdown.setObjectName("spinBox_drawdown")
        self.gridLayout_5.addWidget(self.spinBox_drawdown, 1, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.gridLayout_5.addWidget(self.label_36, 1, 0, 1, 1)
        self.spinBox_volatility = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_volatility.setMinimum(30)
        self.spinBox_volatility.setMaximum(500)
        self.spinBox_volatility.setObjectName("spinBox_volatility")
        self.gridLayout_5.addWidget(self.spinBox_volatility, 0, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.gridLayout_5.addWidget(self.label_35, 0, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.gridLayout_5.addWidget(self.label_37, 1, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 7, 5, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.tab_4)
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout_4.addWidget(self.line_16, 2, 3, 9, 1)
        self.mpl_returns = MplSubPlotWidget(self.tab_4)
        self.mpl_returns.setObjectName("mpl_returns")
        self.gridLayout_4.addWidget(self.mpl_returns, 3, 4, 8, 1)
        self.mpl_vol = MplWidget(self.tab_4)
        self.mpl_vol.setObjectName("mpl_vol")
        self.gridLayout_4.addWidget(self.mpl_vol, 3, 5, 4, 1)
        self.gridLayout_4.setColumnMinimumWidth(4, 1000)
        self.gridLayout_4.setColumnMinimumWidth(5, 1000)
        self.gridLayout_8.addLayout(self.gridLayout_4, 0, 3, 8, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_11.addWidget(self.label_19, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_11.addWidget(self.label_20, 0, 1, 1, 1)
        self.Portfolio_Select = QtWidgets.QComboBox(self.tab_4)
        self.Portfolio_Select.setObjectName("Portfolio_Select")
        self.gridLayout_11.addWidget(self.Portfolio_Select, 1, 0, 1, 1)
        self.startDate_2 = QtWidgets.QDateEdit(self.tab_4)
        self.startDate_2.setCalendarPopup(True)
        self.startDate_2.setDate(QtCore.QDate(2010, 1, 1))
        self.startDate_2.setObjectName("startDate_2")
        self.gridLayout_11.addWidget(self.startDate_2, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_11.addWidget(self.label_18, 2, 1, 1, 1)
        self.endDate_2 = QtWidgets.QDateEdit(self.tab_4)
        self.endDate_2.setCalendarPopup(True)
        self.endDate_2.setDate(QtCore.QDate(2015, 1, 1))
        self.endDate_2.setObjectName("endDate_2")
        self.gridLayout_11.addWidget(self.endDate_2, 3, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_11, 0, 0, 2, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.bck_returns_label = QtWidgets.QLabel(self.tab_4)
        self.bck_returns_label.setObjectName("bck_returns_label")
        self.gridLayout_6.addWidget(self.bck_returns_label, 3, 2, 1, 1)
        self.bck_DD_label = QtWidgets.QLabel(self.tab_4)
        self.bck_DD_label.setObjectName("bck_DD_label")
        self.gridLayout_6.addWidget(self.bck_DD_label, 7, 2, 1, 1)
        self.bck_volatility_label = QtWidgets.QLabel(self.tab_4)
        self.bck_volatility_label.setObjectName("bck_volatility_label")
        self.gridLayout_6.addWidget(self.bck_volatility_label, 4, 2, 1, 1)
        self.port_Beta_label = QtWidgets.QLabel(self.tab_4)
        self.port_Beta_label.setObjectName("port_Beta_label")
        self.gridLayout_6.addWidget(self.port_Beta_label, 9, 1, 1, 1)
        self.bck_Sharpe_label = QtWidgets.QLabel(self.tab_4)
        self.bck_Sharpe_label.setObjectName("bck_Sharpe_label")
        self.gridLayout_6.addWidget(self.bck_Sharpe_label, 6, 2, 1, 1)
        self.bck_Beta_label = QtWidgets.QLabel(self.tab_4)
        self.bck_Beta_label.setObjectName("bck_Beta_label")
        self.gridLayout_6.addWidget(self.bck_Beta_label, 9, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_6.addWidget(self.label_27, 2, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 3, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_6.addWidget(self.label_28, 2, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_6.addWidget(self.label_24, 6, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 7, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 4, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_6.addWidget(self.label_29, 8, 0, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.tab_4)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_6.addWidget(self.line_14, 1, 0, 1, 3)
        self.label_26 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 9, 0, 1, 1)
        self.port_volatility_label = QtWidgets.QLabel(self.tab_4)
        self.port_volatility_label.setObjectName("port_volatility_label")
        self.gridLayout_6.addWidget(self.port_volatility_label, 4, 1, 1, 1)
        self.port_DD_label = QtWidgets.QLabel(self.tab_4)
        self.port_DD_label.setObjectName("port_DD_label")
        self.gridLayout_6.addWidget(self.port_DD_label, 7, 1, 1, 1)
        self.port_returns_label = QtWidgets.QLabel(self.tab_4)
        self.port_returns_label.setObjectName("port_returns_label")
        self.gridLayout_6.addWidget(self.port_returns_label, 3, 1, 1, 1)
        self.port_Sharpe_label = QtWidgets.QLabel(self.tab_4)
        self.port_Sharpe_label.setObjectName("port_Sharpe_label")
        self.gridLayout_6.addWidget(self.port_Sharpe_label, 6, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 0, 0, 1, 3)
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 5, 0, 1, 1)
        self.port_TE_label = QtWidgets.QLabel(self.tab_4)
        self.port_TE_label.setObjectName("port_TE_label")
        self.gridLayout_6.addWidget(self.port_TE_label, 5, 1, 1, 1)
        self.bck_TE_label = QtWidgets.QLabel(self.tab_4)
        self.bck_TE_label.setObjectName("bck_TE_label")
        self.gridLayout_6.addWidget(self.bck_TE_label, 5, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_6, 2, 0, 6, 2)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_33 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_12.addWidget(self.label_33, 0, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.gridLayout_12.addWidget(self.label_39, 0, 1, 1, 1)
        self.Portfolio_Select_2 = QtWidgets.QComboBox(self.tab)
        self.Portfolio_Select_2.setObjectName("Portfolio_Select_2")
        self.gridLayout_12.addWidget(self.Portfolio_Select_2, 1, 0, 1, 1)
        self.startDate_3 = QtWidgets.QDateEdit(self.tab)
        self.startDate_3.setCalendarPopup(True)
        self.startDate_3.setDate(QtCore.QDate(2010, 1, 1))
        self.startDate_3.setObjectName("startDate_3")
        self.gridLayout_12.addWidget(self.startDate_3, 1, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.gridLayout_12.addWidget(self.label_40, 2, 1, 1, 1)
        self.endDate_3 = QtWidgets.QDateEdit(self.tab)
        self.endDate_3.setCalendarPopup(True)
        self.endDate_3.setDate(QtCore.QDate(2015, 1, 1))
        self.endDate_3.setObjectName("endDate_3")
        self.gridLayout_12.addWidget(self.endDate_3, 3, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.mpl_2 = MplWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_2.sizePolicy().hasHeightForWidth())
        self.mpl_2.setSizePolicy(sizePolicy)
        self.mpl_2.setMinimumSize(QtCore.QSize(850, 150))
        self.mpl_2.setObjectName("mpl_2")
        self.gridLayout_14.addWidget(self.mpl_2, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_14, 0, 1, 1, 1)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.mpl_3 = MplWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_3.sizePolicy().hasHeightForWidth())
        self.mpl_3.setSizePolicy(sizePolicy)
        self.mpl_3.setMinimumSize(QtCore.QSize(850, 150))
        self.mpl_3.setObjectName("mpl_3")
        self.gridLayout_15.addWidget(self.mpl_3, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_15, 1, 1, 1, 1)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.mpl_4 = MplWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_4.sizePolicy().hasHeightForWidth())
        self.mpl_4.setSizePolicy(sizePolicy)
        self.mpl_4.setMinimumSize(QtCore.QSize(850, 150))
        self.mpl_4.setObjectName("mpl_4")
        self.gridLayout_16.addWidget(self.mpl_4, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_16, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_9.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1137, 21))
        self.menubar.setObjectName("menubar")
        self.menuFiile = QtWidgets.QMenu(self.menubar)
        self.menuFiile.setObjectName("menuFiile")
        self.menuImport_Benchmark = QtWidgets.QMenu(self.menuFiile)
        self.menuImport_Benchmark.setObjectName("menuImport_Benchmark")
        self.menuAction = QtWidgets.QMenu(self.menubar)
        self.menuAction.setObjectName("menuAction")
        self.menuExport_Graphic = QtWidgets.QMenu(self.menuAction)
        self.menuExport_Graphic.setObjectName("menuExport_Graphic")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_Portfolio = QtWidgets.QAction(MainWindow)
        self.actionImport_Portfolio.setObjectName("actionImport_Portfolio")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionHistoric_datas = QtWidgets.QAction(MainWindow)
        self.actionHistoric_datas.setObjectName("actionHistoric_datas")
        self.actionHistoric_Composition = QtWidgets.QAction(MainWindow)
        self.actionHistoric_Composition.setObjectName("actionHistoric_Composition")
        self.actionHistoric_Index = QtWidgets.QAction(MainWindow)
        self.actionHistoric_Index.setObjectName("actionHistoric_Index")
        self.actionRefresh_Context = QtWidgets.QAction(MainWindow)
        self.actionRefresh_Context.setObjectName("actionRefresh_Context")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionPerformances = QtWidgets.QAction(MainWindow)
        self.actionPerformances.setObjectName("actionPerformances")
        self.actionTurnover = QtWidgets.QAction(MainWindow)
        self.actionTurnover.setObjectName("actionTurnover")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menuImport_Benchmark.addAction(self.actionHistoric_datas)
        self.menuImport_Benchmark.addAction(self.actionHistoric_Composition)
        self.menuImport_Benchmark.addAction(self.actionHistoric_Index)
        self.menuFiile.addAction(self.actionImport_Portfolio)
        self.menuFiile.addAction(self.menuImport_Benchmark.menuAction())
        self.menuFiile.addAction(self.actionSave)
        self.menuFiile.addAction(self.actionNew)
        self.menuExport_Graphic.addAction(self.actionPerformances)
        self.menuExport_Graphic.addAction(self.actionTurnover)
        self.menuExport_Graphic.addAction(self.action)
        self.menuAction.addAction(self.actionRefresh_Context)
        self.menuAction.addAction(self.menuExport_Graphic.menuAction())
        self.menubar.addAction(self.menuFiile.menuAction())
        self.menubar.addAction(self.menuAction.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Start Date"))
        self.UniverseSelect.setItemText(0, _translate("MainWindow", "MSCI EU"))
        self.UniverseSelect.setItemText(1, _translate("MainWindow", "MSCI Europe"))
        self.UniverseSelect.setItemText(2, _translate("MainWindow", "STOXX 50"))
        self.endDate.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.label_3.setText(_translate("MainWindow", "End Date"))
        self.Button_Import_Data.setText(_translate("MainWindow", "Data"))
        self.startDate.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.label.setText(_translate("MainWindow", "Universe"))
        self.pushButton.setText(_translate("MainWindow", "Launch"))
        self.label_10.setText(_translate("MainWindow", "Historic Length"))
        self.radioButton_4.setText(_translate("MainWindow", "1 / Sigma"))
        self.label_7.setText(_translate("MainWindow", "Rebalancing Frequency"))
        self.label_15.setText(_translate("MainWindow", "Add to Backtest List"))
        self.label_4.setText(_translate("MainWindow", "Weight Constraints"))
        self.label_8.setText(_translate("MainWindow", "Portfolio Parameters"))
        self.label_5.setText(_translate("MainWindow", "Minimum"))
        self.label_9.setText(_translate("MainWindow", "Months"))
        self.radioButton_3.setText(_translate("MainWindow", "1 / Beta"))
        self.label_11.setText(_translate("MainWindow", "Months"))
        self.Button_Import_Compo.setText(_translate("MainWindow", "Compo"))
        self.label_56.setText(_translate("MainWindow", "... More to Come"))
        self.label_6.setText(_translate("MainWindow", "Maximum"))
        self.label_43.setText(_translate("MainWindow", "Backtest Parameters"))
        self.Button_Import_Index.setText(_translate("MainWindow", "Index"))
        self.radioButton.setText(_translate("MainWindow", "Min Variance"))
        self.label_16.setText(_translate("MainWindow", "Reset the Backtest List"))
        self.Button_Reset.setText(_translate("MainWindow", "Reset"))
        self.label_14.setText(_translate("MainWindow", "Start Date"))
        self.label_17.setText(_translate("MainWindow", "Strategy "))
        self.Button_Add_Port.setText(_translate("MainWindow", "OK"))
        self.radioButton_2.setText(_translate("MainWindow", "Equal Weighted"))
        self.label_13.setText(_translate("MainWindow", "End Date"))
        self.Graph_startDate.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.label_38.setText(_translate("MainWindow", "Save the Backtest"))
        self.Graph_Update.setText(_translate("MainWindow", "Refresh"))
        self.Graph_endDate.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.Button_Save.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Settings"))
        self.label_30.setText(_translate("MainWindow", "Returns Analysis"))
        self.label_31.setText(_translate("MainWindow", "Vol Analysis"))
        self.label_32.setText(_translate("MainWindow", "Distribution"))
        self.label_34.setText(_translate("MainWindow", "Volatility"))
        self.label_36.setText(_translate("MainWindow", "Drawdown"))
        self.label_35.setText(_translate("MainWindow", "Days"))
        self.label_37.setText(_translate("MainWindow", "Days"))
        self.label_19.setText(_translate("MainWindow", "Portoflio"))
        self.label_20.setText(_translate("MainWindow", "From"))
        self.startDate_2.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.label_18.setText(_translate("MainWindow", "To"))
        self.endDate_2.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.bck_returns_label.setText(_translate("MainWindow", "0"))
        self.bck_DD_label.setText(_translate("MainWindow", "0"))
        self.bck_volatility_label.setText(_translate("MainWindow", "-"))
        self.port_Beta_label.setText(_translate("MainWindow", "0"))
        self.bck_Sharpe_label.setText(_translate("MainWindow", "0"))
        self.bck_Beta_label.setText(_translate("MainWindow", "0"))
        self.label_27.setText(_translate("MainWindow", "Portfolio"))
        self.label_22.setText(_translate("MainWindow", "Returns"))
        self.label_28.setText(_translate("MainWindow", "Benchmark"))
        self.label_24.setText(_translate("MainWindow", "Sharpe Ratio"))
        self.label_25.setText(_translate("MainWindow", "Max Drawdown"))
        self.label_23.setText(_translate("MainWindow", "Volatility"))
        self.label_29.setText(_translate("MainWindow", "Recovery"))
        self.label_26.setText(_translate("MainWindow", "Beta"))
        self.port_volatility_label.setText(_translate("MainWindow", "-"))
        self.port_DD_label.setText(_translate("MainWindow", "0"))
        self.port_returns_label.setText(_translate("MainWindow", "0"))
        self.port_Sharpe_label.setText(_translate("MainWindow", "0"))
        self.label_21.setText(_translate("MainWindow", "Risk Metrics"))
        self.label_12.setText(_translate("MainWindow", "Tracking Error"))
        self.port_TE_label.setText(_translate("MainWindow", "-"))
        self.bck_TE_label.setText(_translate("MainWindow", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Risk Analysis"))
        self.label_33.setText(_translate("MainWindow", "Portoflio"))
        self.label_39.setText(_translate("MainWindow", "From"))
        self.startDate_3.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.label_40.setText(_translate("MainWindow", "To"))
        self.endDate_3.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Rebalancing Analysis"))
        self.menuFiile.setTitle(_translate("MainWindow", "File"))
        self.menuImport_Benchmark.setTitle(_translate("MainWindow", "Import Benchmark"))
        self.menuAction.setTitle(_translate("MainWindow", "Action"))
        self.menuExport_Graphic.setTitle(_translate("MainWindow", "Export Graphic"))
        self.actionImport_Portfolio.setText(_translate("MainWindow", "Import Portfolio"))
        self.actionImport_Portfolio.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionHistoric_datas.setText(_translate("MainWindow", "Historic Composant data"))
        self.actionHistoric_Composition.setText(_translate("MainWindow", "Historic Composition"))
        self.actionHistoric_Index.setText(_translate("MainWindow", "Historic Index"))
        self.actionRefresh_Context.setText(_translate("MainWindow", "Refresh Context"))
        self.actionRefresh_Context.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionPerformances.setText(_translate("MainWindow", "Performances"))
        self.actionTurnover.setText(_translate("MainWindow", "Turnover"))
        self.action.setText(_translate("MainWindow", "..."))

from mplsubplotwidget import MplSubPlotWidget
from mplwidget import MplWidget
