# -*- coding: utf-8 -*-
"""
Created on Mon Jun 26 17:16:37 2017

@author: jb.frisch
"""
Ticker_GermanCurve = ['GTDEM1M Govt',
                      'GTDEM3M Govt',
                      'GTDEM6M Govt',
                      'GTDEM1Y Govt',
                      'GTDEM3Y Govt',
                      'GTDEM5Y Govt',
                      'GTDEM10Y Govt',
                      'GTDEM20Y Govt',
                      'GTDEM30Y Govt']

Ticker_Stoxx50 = ['ABI BB Equity',
                'AD NA Equity',
                'ADS GY Equity',
                'AI FP Equity',
                'AIR FP Equity',
                'ALV GY Equity',
                'ASML NA Equity',
                'BAS GY Equity',
                'BAYN GY Equity',
                'BBVA SQ Equity',
                'BMW GY Equity',
                'BN FP Equity',
                'BNP FP Equity',
                'CRH ID Equity',
                'CS FP Equity',
                'DAI GY Equity',
                'DBK GY Equity',
                'DG FP Equity',
                'DPW GY Equity',
                'DTE GY Equity',
                'EI FP Equity',
                'ENEL IM Equity',
                'ENGI FP Equity',
                'ENI IM Equity',
                'EOAN GY Equity',
                'FP FP Equity',
                'FRE GY Equity',
                'GLE FP Equity',
                'IBE SQ Equity',
                'INGA NA Equity',
                'ISP IM Equity',
                'ITX SQ Equity',
                'MC FP Equity',
                'MUV2 GY Equity',
                'NOKIA FH Equity',
                'OR FP Equity',
                'ORA FP Equity',
                'PHIA NA Equity',
                'SAF FP Equity',
                'SAN FP Equity',
                'SAN SQ Equity',
                'SAP GY Equity',
                'SGO FP Equity',
                'SIE GY Equity',
                'SU FP Equity',
                'TEF SQ Equity',
                'UL NA Equity',
                'UNA NA Equity',
                'VIV FP Equity',
                'VOW3 GY Equity']
